apiVersion: v2
appVersion: "1.0"
description: A Helm chart for civil-wa-task-configuration
name: civil-task-configuration
home: https://github.com/hmcts/civil-wa-task-configuration
version: 0.0.5
maintainers:
  - name: HMCTS CIVIL team
dependencies:
  - name: java
    version: 4.0.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: 8.0.17
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - civil-ccd-stack
  - name: xui-webapp
    version: ~1.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: ~2.2.3
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
  - name: postgresql
    version: ~10.16.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: camunda-bpm
    version: 0.0.28
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: camunda-bpm.enabled