module.exports = {
    name: 'Directions after Judgment (Damages)',
    type: 'summaryJudgmentDirections',
    task_title: 'Directions after Judgment (Damages)',
    location_name: 'Barnet Civil and Family Centre',
    location: '229786',
    execution_type: 'Case Management Task',
    jurisdiction: 'CIVIL',
    region: '1',
    case_type_id: 'CIVIL',
    case_category: 'Civil',
    auto_assigned: false,
    case_management_category: 'Civil',
    work_type_id: 'decision_making_work',
    work_type_label: 'Decision-making work',
    permissions: { values: [  'Read', 'Own', 'Manage', 'Cancel', 'CompleteOwn', 'CancelOwn', 'Claim', 'Unclaim', 'Assign', 'Unassign', 'UnclaimAssign' ] },
    description: '[Directions after Judgment (Damages)](/cases/case-details/${[CASE_REFERENCE]}/trigger/STANDARD_DIRECTION_ORDER_DJ/STANDARD_DIRECTION_ORDER_DJCaseManagementOrder)',
    role_category: 'JUDICIAL',
    minor_priority: 500,
    major_priority: 5000
};
