apiVersion: v2
appVersion: "1.0"
description: A Helm chart for civil-wa-task-configuration
name: civil-ia-task-configuration
home: https://github.com/hmcts/civil-wa-task-configuration
version: 0.0.4
maintainers:
  - name: HMCTS CIVIL team
dependencies:
  - name: java
    version: 4.0.1
    repository: '@hmctspublic'
