apiVersion: v2
appVersion: "1.0"
description: A Helm chart for civil-wa-task-configuration
name: ia-task-configuration
home: https://github.com/hmcts/civil-wa-task-configuration
version: 0.0.4
maintainers:
  - name: HMCTS IA team
dependencies:
  - name: java
    version: 3.7.2
    repository: '@hmctspublic'
